# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo {c:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.srcs/sources_1/imports/new/AdderSubtractor.vhd}
  {C:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.srcs/sources_1/imports/new/Adder_3.vhd}
  {C:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.srcs/sources_1/imports/new/D_FF.vhd}
  {C:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.srcs/sources_1/imports/new/D_FF_EN.vhd}
  {C:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.srcs/sources_1/imports/new/Decoder_2_to_4.vhd}
  {C:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.srcs/sources_1/imports/new/Decoder_3_to_8.vhd}
  {C:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.srcs/sources_1/imports/new/FA.vhd}
  {C:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.srcs/sources_1/imports/new/HA.vhd}
  {C:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.srcs/sources_1/imports/new/Instruction_Decoder.vhd}
  {C:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.srcs/sources_1/imports/new/Mux_2_to_1.vhd}
  {C:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.srcs/sources_1/imports/new/Mux_2way_3bit.vhd}
  {C:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.srcs/sources_1/imports/new/Mux_2way_4bit.vhd}
  {C:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.srcs/sources_1/imports/new/Mux_8_to_1.vhd}
  {C:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.srcs/sources_1/imports/new/Mux_8way_4bit.vhd}
  {C:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.srcs/sources_1/imports/new/PC.vhd}
  {C:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.srcs/sources_1/imports/new/ProgramROM.vhd}
  {C:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.srcs/sources_1/imports/new/Reg.vhd}
  {C:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.srcs/sources_1/imports/new/Reg_bank.vhd}
  {C:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.srcs/sources_1/imports/new/Seven_Segment.vhd}
  {C:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.srcs/sources_1/imports/new/Slow_Clock.vhd}
  {C:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.srcs/sources_1/new/Nano_Processor.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.srcs/constrs_1/imports/Downloads/Basys3Labs.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Mr Local/Downloads/Nano_Processor2/Nano_Processor2/Nano_Processor.srcs/constrs_1/imports/Downloads/Basys3Labs.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Nano_Processor -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Nano_Processor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Nano_Processor_utilization_synth.rpt -pb Nano_Processor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
